"""
generate_terraform handler

Takes the raw Terraform snippet from Bedrock and assembles it into
a complete, validatable Terraform file with provider configuration,
required_providers block, and variable declarations.

Input:  Full pipeline state ($.normalized + $.enriched + $.remediation)
Output: dict with the complete Terraform file content and metadata
"""

import logging
import os
import re

logger = logging.getLogger()
logger.setLevel(logging.INFO)

AWS_PROVIDER_VERSION = os.environ.get(
    "AWS_PROVIDER_VERSION", "~> 5.0"
)

TERRAFORM_HEADER = """# Auto-generated by TerraDriftGuard
# Drift remediation for: {config_rule_name}
# Resource: {resource_type} / {resource_id}
# Region: {region}
# Generated: {detected_at}
#
# Review this file before applying. This is a proposed fix,
# not an automatic remediation.

terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "{provider_version}"
    }}
  }}
}}

provider "aws" {{
  region = "{region}"
}}

"""


def handler(event, context):
    """
    Assemble a complete Terraform file from the Bedrock snippet.

    Args:
        event: Full pipeline state
        context: Lambda context (unused)

    Returns:
        dict with terraformFile, filename, and metadata
    """
    normalized = event["normalized"]
    remediation = event["remediation"]

    snippet = remediation.get("terraformSnippet", "")
    plan = remediation.get("plan", {})

    if not snippet.strip():
        logger.warning(
            "Empty Terraform snippet for resource=%s, "
            "using plan REMEDIATION as fallback",
            normalized["resourceId"],
        )
        snippet = _extract_hcl_from_text(
            plan.get("REMEDIATION", "")
        )

    snippet = _clean_snippet(snippet)

    header = TERRAFORM_HEADER.format(
        config_rule_name=normalized["configRuleName"],
        resource_type=normalized["resourceType"],
        resource_id=normalized["resourceId"],
        region=normalized["region"],
        detected_at=normalized["detectedAt"],
        provider_version=AWS_PROVIDER_VERSION,
    )

    terraform_file = header + snippet + "\n"

    filename = _generate_filename(normalized)

    logger.info(
        "Generated Terraform file=%s length=%d for resource=%s",
        filename,
        len(terraform_file),
        normalized["resourceId"],
    )

    return {
        "terraformFile": terraform_file,
        "filename": filename,
        "resourceId": normalized["resourceId"],
        "configRuleName": normalized["configRuleName"],
        "summary": plan.get("SUMMARY", ""),
    }


def _clean_snippet(snippet):
    """
    Remove markdown fencing and leading/trailing whitespace
    that LLMs sometimes include despite instructions.
    """
    cleaned = re.sub(
        r"^```(?:hcl|terraform)?\s*\n?", "", snippet.strip()
    )
    cleaned = re.sub(r"\n?```\s*$", "", cleaned)
    return cleaned.strip()


def _extract_hcl_from_text(text):
    """
    Attempt to extract an HCL block from free-form text.

    Looks for content between triple backticks first,
    then falls back to lines that look like Terraform
    resource definitions.
    """
    fenced = re.search(
        r"```(?:hcl|terraform)?\s*\n(.*?)\n```",
        text,
        re.DOTALL,
    )
    if fenced:
        return fenced.group(1).strip()

    resource_block = re.search(
        r'(resource\s+"[^"]+"\s+"[^"]+"\s*\{.*?\n\})',
        text,
        re.DOTALL,
    )
    if resource_block:
        return resource_block.group(1).strip()

    logger.warning("Could not extract HCL from text, returning as-is")
    return f"# WARNING: Could not parse Terraform from LLM output\n# Raw text:\n# {text}"


def _generate_filename(normalized):
    """
    Generate a descriptive filename for the remediation file.

    Format: remediate_{rule}_{resource_id}.tf
    """
    rule = re.sub(r"[^a-zA-Z0-9_]", "_", normalized["configRuleName"])
    resource = re.sub(r"[^a-zA-Z0-9_]", "_", normalized["resourceId"])
    return f"remediate_{rule}_{resource}.tf"
