"""
Tests for lambda/generate_terraform/handler.py

Validates Terraform file assembly, snippet cleaning, and fallback extraction.
"""

from generate_terraform.handler import handler, _clean_snippet, _extract_hcl_from_text, _generate_filename


class TestSnippetCleaning:
    """Verify markdown fencing and whitespace removal."""

    def test_strips_hcl_fencing(self):
        raw = '```hcl\nresource "aws_s3_bucket" "test" {}\n```'
        assert _clean_snippet(raw) == 'resource "aws_s3_bucket" "test" {}'

    def test_strips_terraform_fencing(self):
        raw = '```terraform\nresource "aws_s3_bucket" "test" {}\n```'
        assert _clean_snippet(raw) == 'resource "aws_s3_bucket" "test" {}'

    def test_strips_bare_fencing(self):
        raw = '```\nresource "aws_s3_bucket" "test" {}\n```'
        assert _clean_snippet(raw) == 'resource "aws_s3_bucket" "test" {}'

    def test_no_fencing_passes_through(self):
        raw = 'resource "aws_s3_bucket" "test" {}'
        assert _clean_snippet(raw) == raw

    def test_strips_surrounding_whitespace(self):
        raw = '\n\n  resource "aws_s3_bucket" "test" {}  \n\n'
        assert _clean_snippet(raw) == 'resource "aws_s3_bucket" "test" {}'


class TestHclExtraction:
    """Verify fallback extraction from free-form text."""

    def test_extracts_from_fenced_block(self):
        text = 'Here is the fix:\n```hcl\nresource "aws_s3_bucket" "fix" {\n  bucket = "test"\n}\n```\nApply this.'
        result = _extract_hcl_from_text(text)
        assert result.startswith("resource")
        assert "test" in result

    def test_extracts_resource_block_without_fencing(self):
        text = 'You should use:\nresource "aws_security_group_rule" "fix" {\n  type = "ingress"\n}\nThat will work.'
        result = _extract_hcl_from_text(text)
        assert "aws_security_group_rule" in result

    def test_returns_warning_when_no_hcl_found(self):
        text = "Just remove the rule manually."
        result = _extract_hcl_from_text(text)
        assert "WARNING" in result


class TestFilenameGeneration:
    """Verify filename format."""

    def test_sg_filename(self, normalized_sg):
        result = _generate_filename(normalized_sg)
        assert result == "remediate_restricted_ssh_sg_0a1b2c3d4e5f67890.tf"

    def test_special_characters_replaced(self):
        normalized = {
            "configRuleName": "my-custom-rule",
            "resourceId": "arn:aws:s3:::my-bucket",
        }
        result = _generate_filename(normalized)
        assert "/" not in result
        assert ":" not in result


class TestFullAssembly:
    """Verify complete Terraform file generation."""

    def test_includes_provider_block(self, full_pipeline_state):
        result = handler(full_pipeline_state, None)

        assert 'required_providers' in result["terraformFile"]
        assert 'hashicorp/aws' in result["terraformFile"]

    def test_includes_region(self, full_pipeline_state):
        result = handler(full_pipeline_state, None)

        assert 'region = "us-east-1"' in result["terraformFile"]

    def test_includes_snippet(self, full_pipeline_state):
        result = handler(full_pipeline_state, None)

        assert "aws_security_group_rule" in result["terraformFile"]

    def test_includes_comment_header(self, full_pipeline_state):
        result = handler(full_pipeline_state, None)

        assert "Auto-generated by TerraDriftGuard" in result["terraformFile"]
        assert "restricted-ssh" in result["terraformFile"]

    def test_returns_filename(self, full_pipeline_state):
        result = handler(full_pipeline_state, None)

        assert result["filename"].endswith(".tf")

    def test_empty_snippet_uses_fallback(self, full_pipeline_state):
        full_pipeline_state["remediation"]["terraformSnippet"] = ""

        result = handler(full_pipeline_state, None)

        assert len(result["terraformFile"]) > 0
